name: bump

on:
  push:
    branches:
      - main

jobs:
  version:
    name: Bumping pkg version
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
