name: bump

on:
  push:
    branches:
      - main

jobs:
  version:
    permissions: write-all
    name: Bumping pkg version
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[bump:pkg]')"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - run: npm version patch -m "[bump:pkg] %s"
      - run: git push
