name: ci + cd

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    name: lint changeset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: npm install and lint
        run: |
          npm install
          npm run lint

  test:
    name: test changeset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: npm install and test
        run: |
          npm install
          npm run test

  publish:
    name: publish build
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: npm install and publish
        run: |
          npm install
          npm run publish
