name: release

on:
  push:
    tags:
      - '*'

jobs:
  lint:
    name: Running linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install dependencies and run linter
        run: |
          npm install
          npm run lint

  test:
    name: Running unit testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install dependencies and run unit test
        run: |
          npm install
          npm run test

  publish:
    name: Publishing pkg
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install dependencies
        run: npm install
      - name: configure npm registry as publish target
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
      - name: publish to npm registry
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PUBLISH_GPR_TOKEN }}
